### PR TITLE
Social Media Distractor Personal Project

### PR DESCRIPTION
**Pull request by Developer-Amritanshu**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by sudhanshutiwari264 — APPROVED** [review]
@Developer-Amritanshu 
This is a really great idea, and your work is really commendable!

**Review by theAdityaNVS — APPROVED** [review]
Wow @Developer-Amritanshu ,
Your Idea is great and yes it'll surely help to control social media consumption.
- One suggestion for future iteration of your build, Try to make your Password text files encrypted and hidden in some directory.

**Comment by Developer-Amritanshu** [comment]
Thanks :)

**Comment by Developer-Amritanshu** [comment]
@theAdityaNVS 

Yes sir, I have that thought of storing passwords in hash and using salts but our college is scheduling our classes for placement and I was also working on some other projects. so, I didn't add that functionality but I will keep that in mind for upcoming projects.

Thanks :)

**Comment by Nitesh-thapliyal** [comment]
Hey @Developer-Amritanshu  Nice work 👏

Here is  a suggestion that you can work on:

- Can you create a front-end for the application so that users can also use the application to add their own credentials and connect the backend too.

**Note:** It is not compulsory but if you can do then well and good  ⭐

**Comment by Developer-Amritanshu** [comment]
@Nitesh-thapliyal Thank you, Sir :)

Yes Sir, If I get some free time I will apply that.

**Comment by archithdwij** [comment]
Hi @Developer-Amritanshu Great work! Congratulations on getting your PR merged! Add the suggested feature of creating a front end to this so that adding credentials would be more dynamic. You can do it whenever time permits.

**Review by archithdwij — APPROVED** [review]

**Comment by archithdwij** [comment]
@all-contributors Please Add @Developer-Amritanshu for code, idea, infra, design

**Pull request merged**
