### PR TITLE
GitNote-Bot Files

### PR DESCRIPTION
**Pull request by PranavPrakasan07**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [ ] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [ ]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you receive communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provided here. All the best :)

### CODE REVIEW

**Review by sudhanshutiwari264 — COMMENTED** [review]
@PranavPrakasan07, your project looks great :+1: 
However, it would be great if you could add a demo video!

**Comment by PranavPrakasan07** [comment]
Thank you, sure, I'll make a demo video.

**Comment by archithdwij** [comment]
@PranavPrakasan07 We are gonna go ahead and merge your PR but we highly recommend you to upload your demo video ASAP.

**Comment by archithdwij** [comment]
@all-contributors Please add @PranavPrakasan07 for idea, infra, design, code

**Comment by PranavPrakasan07** [comment]
Thank you for merging my PR! I have added the demo video also.

**Pull request merged**
