### PR TITLE
MS-Teams-Automation

### PR DESCRIPTION
**Pull request by DikshitReddy**
## Pull Request Checklist

Go through the check boxes given below and make sure you mark the relevant ones.
#### To check put x inside [ ] eg. [x] Extension

Is your project an
- [] Extension 
- [x] Application

Given below are the mandatory requirements we expect from your project. Your Pull Request will be reviewed only if all the minimum requirements relevant to your project are satisfied.

- [x] Added readme.md to my project folder with relevant information.
- [x]  I have provided the demo video link (showing the functionality in action) or the public deployment link of my extension of application within the readme.md (if Applicable).
- [x] I have explained the process in a readable manner within readme.md.

### Terms and Conditions

`Plagiarism check from Team Crio will be solid and if your code is found to be plagiarized, the team has every right to reject your Pull Request and take necessary actions.`
- [x] I can assure you that this is my own contribution and I did not involve in any kind of plagiarism activities.

Buckle up and wait till you recieve communication from the review team. Keep a tab on this pull request page for comments on your project. Any necessary suggestions will also be provide here. All the best :)

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Nice work @DikshitReddy  but can you make a full demo video presenting all functionality of the application as mentioned in the readme and can you make the demo video with a voice explaining the process and functionality of the application.

**Comment by DikshitReddy** [comment]
> Nice work @DikshitReddy but can you make a full demo video presenting all functionality of the application as mentioned in the readme and can you make the demo video with a voice explaining the process and functionality of the application.

yes ill try to explain but i've shown the things very clear which were required. Thank you:)

**Comment by Nitesh-thapliyal** [comment]
> > Nice work @DikshitReddy but can you make a full demo video presenting all functionality of the application as mentioned in the readme and can you make the demo video with a voice explaining the process and functionality of the application.
> 
> yes ill try to explain but i've shown the things very clear which were required. Thank you:)

If we can see all the functionality that you mentioned in the readme will make it easy for us to understand

**Comment by DikshitReddy** [comment]
Demonstartion video link updated 👍.

**Review by sudhanshutiwari264 — APPROVED** [review]
@DikshitReddy thanks for making the requested changes!
Your work is  awesome :tada: 
LGTM!

**Comment by Nitesh-thapliyal** [comment]
Hey, @DikshitReddy nice explanation

but can you demonstrate all features that you mentioned in the readme, like automatically joining the meet and when the host leaves then the user also automatically leave based on the decrease in participants. If you want any help in the demonstration (like we can be participants) do reach out to us.

**Review by Nitesh-thapliyal — COMMENTED** [review]
Hey, @DikshitReddy nice explanation

but can you demonstrate all features that you mentioned in the readme, like automatically joining the meet and when the host leaves then the user also automatically leave based on the decrease in participants. If you want any help in the demonstration (like we can be participants) do reach out to us.

**Review by SulthanNK — APPROVED** [review]
Kudos to your work 🎉 @DikshitReddy

**Comment by DikshitReddy** [comment]
Yes sir! Ive already explained all the features of my project and showed that how much i can and still many features can be added but now i worked only on automating login  and attending meet and it leaves the meet by default. Thank you.

**Comment by Nitesh-thapliyal** [comment]
> Yes sir! Ive already explained all the features of my project and showed that how much i can and still many features can be added but now i worked only on automating login and attending meet and it leaves the meet by default. Thank you.

You have done amazing work but the feature that you mentioned in the readme is great, if we can see them in the demo video that will be helpful. Does the other functionality that you mentioned in readme works?  to know that we need to see demo video that is the purpose of demo video but No problem if you are not able to demonstrate that.

**Review by Nitesh-thapliyal — APPROVED** [review]

**Comment by plagiarism-check** [comment]
@Nitesh-thapliyal @SulthanNK @sudhanshutiwari264, the user Dikshit Reddy has copied the code from [https://github.com/atharva-lipare/MS-Teams-Auto-Joiner](https://github.com/atharva-lipare/MS-Teams-Auto-Joiner) line-by-line without crediting the original author. Using open-source code isn't an issue but submitting it as your own creation in a competition is unethical.

He also wrote a medium article in which he claims to have written the code. [Link to backup of that article](https://raw.githubusercontent.com/plagiarism-check/dikshit-reddy-plagiarism/main/Automate%20Microsoft%20Teams%20using%20Python%20and%20Selenium%20framework%20%7C%20by%20Dikshit%20Reddy%20V%20R%20%7C%20Jul%2C%202021%20%7C%20Medium.pdf).

After confronting him about it, he has also used abusive language. [Link to screenshot of the chat](https://raw.githubusercontent.com/plagiarism-check/dikshit-reddy-plagiarism/main/02e5a346-10ab-4051-9332-509c232a4699.jpg).

I hope your team will do plagiarism checks in the future.

**Comment by YourAKShaw** [comment]
@archithdwij @sudhanshutiwari264 @Nitesh-thapliyal Kindly take a look into this issue #11

**Comment by YourAKShaw** [comment]
@plagiarism-check Thank you for bringing this issue to our notice. This helped us in upholding the theme of the event. We appreciate it. 

Although, we have a friendly request to kindly reach out to any of the maintainers prior to commenting right away. 

Thanks again,
Regards.

**Pull request closed without merging**
